### PR TITLE
Ui password email

### PR DESCRIPTION
**Pull request by chalynpai**
image
image

Also fixed a small issue with the messaging page
image

### CODE REVIEW

**Comment by wclui** [comment]
- Can you change the setting dropdown to have round edges?
- maybe style the "You are currently messaging:"
- possibly makes the messaging screen size larger? 
- I might be imagine things, are the "Log Out" styling the same as the others in terms of font-family, font-size, font-weight, etc?

**Review by wclui — CHANGES_REQUESTED** [review]
- Can you change the setting dropdown to have round edges?
- maybe style the "You are currently messaging:"
- possibly makes the messaging screen size larger?
- I might be imagining things, are the "Log Out" styling the same as the others in terms of font-family, font-size, font-weight, etc?

**Review by jj7lin — CHANGES_REQUESTED** [review]
Can send message button be aligned to the right to the end of message box?

Do we want to place visual emphasis on the logout button or should we switch it over to the matches page (usually diff color buttons would = actions we want the users to take more often)

Color for settings drop down seems out of place 

Maybe add ppfriends logo to some of the pages for consistency ?

Instead of changing font colors for the drop down, maybe change the background color and add hover effects for each drop down item. Black color font isn’t as clear compared to white font against that drop down menu color.

Capitalize the “p” in “please enter your new email address”

Can there be similar/consistent spacing between change password heading and old password input box (make it same spacing as update email and please enter email text)

Capitalize first letter of every input box text to keep it consistent

**Comment by chalynpai** [comment]
**For the header:** 
- fixed colouring consistencies
- rounded border edges
- changed logout button colour
- made font sizing consistent
- made hover background

**Password**
- Capitalized first letters
image
**Email**
- Fixed capitalization
- Made outlay similar to change password
image
**Messaging:**
- moved enter message button more right
- styled "you are currently messaging"
- Increased size of messaging box
image

Personally I don't like having the logo on every page, it clutters it and is unnecessary to have it on every page.

**Comment by wclui** [comment]
do you mind adding an arrow next to "Settings", or make an outline to suggest it is a dropdown menu?

**Comment by mnsison** [comment]
- for the dropdown arrow try this? https://www.w3schools.com/howto/howto_css_arrows.asp
image

- Update buttons in change email and password pages are not centered

image

**Comment by mnsison** [comment]
- The names of the users are reversed when messaging
- Should the text box and send button be at the bottom of the container?

image

**Review by echanlee — APPROVED** [review]

**Review by wclui — APPROVED** [review]

**Review by jj7lin — COMMENTED** [review]
Sorry one last feedback - do you think itd be nice to add user's profile pic to messaging? ie. fb messaging has profile pic attached to each message

**Review by jj7lin — APPROVED** [review]

**Pull request merged**
