### PR TITLE
Match UI changes

### PR DESCRIPTION
**Pull request by chalynpai**
image
image
image

image

### CODE REVIEW

**Comment by wclui** [comment]
- Is there any way we can make the page that shows both messaged users and not messaged users more balanced? ex.  make both the "name" | view profile | unmatch and Messaged Users line all centered or left centered.
- If the user only has messaged users or only has not messaged users, could we make it 1 column instead? It might be easier to understand what is going on with left and right. 
- in the "sorry no one met your criteria ..." page, consider making the paragraph centred, since the penguin logo and the buttons are centred too. 
- in the view friend's profile, can we make the profile pic larger or put the name below the photo as well. It looks a bit imbalanced since left side is so much shorter. 
- in view friend's profile page, perhaps make the "View ___ profile" a bit farther from the top?

**Review by wclui — CHANGES_REQUESTED** [review]
- Is there any way we can make the page that shows both messaged users and not messaged users more balanced? ex.  make both the "name" | view profile | unmatch and Messaged Users line all centered or left centered.
- If the user only has messaged users or only has not messaged users, could we make it 1 column instead? It might be easier to understand what is going on with left and right. 
- in the "sorry no one met your criteria ..." page, consider making the paragraph centred, since the penguin logo and the buttons are centred too. 
- in the view friend's profile, can we make the profile pic larger or put the name below the photo as well. It looks a bit imbalanced since left side is so much shorter. 
- in view friend's profile page, perhaps make the "View ___ profile" a bit farther from the top?

**Comment by echanlee** [comment]
- Can you also consider making the unmatch button look more button like
- for the matches page can you distinguish the name more clearly from the buttons. When I was looking at the 'a' user I was confused for a second

**Comment by chalynpai** [comment]
image
image
image
image

**Review by echanlee — APPROVED** [review]

**Review by wclui — APPROVED** [review]

**Pull request merged**
